BEGIN
	SET @guyID = [GUY ID]
	IF @guyID IS NULL 
		BEGIN
			DELETE FROM @guy
			INSERT INTO tnx.guys OUTPUT INSERTED.ID INTO @guy VALUES([ALL GUY VALUES])
			SELECT @guyID = guyID FROM @guy
		END
	INSERT INTO tnx.guys_xref VALUES(@guyID, @tnxID)
END