'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CCI_Engineering_Templates.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CCIpole() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIpole", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''BEGIN
        '''	
        '''	--[SOIL PROFILE INSERT]
        '''
        '''	--[PIER PROFILE INSERT]
        '''
        '''	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
        '''		OUTPUT INSERTED.ID INTO @TopLevel
        '''		VALUES([INSERT VALUES])
        '''	SELECT @TopLevelID=ID FROM @TopLevel
        '''
        '''	--[RESULTS]
        '''
        '''	DELETE FROM @TopLevel --Pier
        '''	DELETE FROM @SubLevel1 --Soil Profile
        '''	DELETE FROM @SubLevel2 --Pier Profile
        '''	DELETE FROM @SubLevel3 --Section
        '''	DELETE FROM @SubLevel4 --File Upload
        '''END.
        '''</summary>
        Friend ReadOnly Property Drilled_Pier__INSERT() As String
            Get
                Return ResourceManager.GetString("Drilled_Pier__INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Drilled_Pier_Foundation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Drilled_Pier_Foundation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEGIN
        '''
        '''	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
        '''		OUTPUT INSERTED.ID INTO @SubLevel2
        '''		VALUES([INSERT VALUES])
        '''	SELECT @SubLevel2ID=ID FROM @SubLevel2
        '''
        '''	--[SECTION INSERT]
        '''
        '''	--[BELLED INSERT]
        '''
        '''	--[EMBEDDED INSERT]
        '''
        '''END.
        '''</summary>
        Friend ReadOnly Property Drilled_Pier_Profile__INSERT() As String
            Get
                Return ResourceManager.GetString("Drilled_Pier_Profile__INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEGIN
        '''
        '''	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
        '''		OUTPUT INSERTED.ID INTO @SubLevel3
        '''		VALUES([INSERT VALUES])
        '''	SELECT @SubLevel3ID=ID FROM @SubLevel3
        '''
        '''	--[REBAR INSERT]
        '''
        '''END.
        '''</summary>
        Friend ReadOnly Property Drilled_Pier_Section__INSERT() As String
            Get
                Return ResourceManager.GetString("Drilled_Pier_Section__INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEGIN
        '''
        '''	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
        '''		OUTPUT INSERTED.ID INTO [SUBLEVEL TABLE]
        '''		VALUES([INSERT VALUES])
        '''	SELECT [SUBLEVEL ID]=ID FROM [SUBLEVEL TABLE]
        '''
        '''	--[REQUIRED CHILDREN]
        '''
        '''END.
        '''</summary>
        Friend ReadOnly Property Drilled_Pier_Tool__INSERT() As String
            Get
                Return ResourceManager.GetString("Drilled_Pier_Tool__INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''BEGIN
        '''	DELETE FROM [TABLE] WHERE ID = [ID]
        '''END.
        '''</summary>
        Friend ReadOnly Property General__DELETE() As String
            Get
                Return ResourceManager.GetString("General__DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEGIN
        '''	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
        '''		VALUES([INSERT VALUES])
        '''END.
        '''</summary>
        Friend ReadOnly Property General__INSERT() As String
            Get
                Return ResourceManager.GetString("General__INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BEGIN
        '''	UPDATE [TABLE NAME]
        '''	SET [UPDATE] 
        '''	WHERE ID = [ID]
        '''
        '''	--[OPTIONAL]
        '''END.
        '''</summary>
        Friend ReadOnly Property General__UPDATE() As String
            Get
                Return ResourceManager.GetString("General__UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pier_and_Pad_Foundation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pier_and_Pad_Foundation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SST_Unit_Base_Foundation() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SST_Unit_Base_Foundation", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
