	BEGIN --[CCIPLATE MATERIAL INSERT BEGIN]
	--[CCIPLATE MATERIAL INSERT]
	END --[CCIPLATE MATERIAL INSERT END]

	INSERT INTO conn.bolt_details ([BOLT DETAIL FIELDS]) 
	VALUES([BOLT DETAIL VALUES])

	--[BOLT DETAIL INSERT]