	UPDATE conn.bolts
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel2ID=[ID]

	--BEGIN --[BOLT DETAIL UPDATE BEGIN]
	--[BOLT DETAIL INSERT]
	--END --[BOLT DETAIL UPDATE END]

	--BEGIN --[BOLT RESULTS INSERT BEGIN]
	--[BOLT RESULTS INSERT]
	--END --[BOLT RESULTS INSERT END]

	--[BOLT GROUP INSERT]