	INSERT INTO conn.bolts ([BOLT GROUP FIELDS]) 
	OUTPUT INSERTED.ID INTO @SubLevel2
	VALUES([BOLT GROUP VALUES])
	SELECT @SubLevel2ID=ID FROM @SubLevel2

	--BEGIN --[BOLT DETAIL INSERT BEGIN]
	--[BOLT DETAIL INSERT]
	--END --[BOLT DETAIL INSERT END]

	--BEGIN --[BOLT RESULTS INSERT BEGIN]
	--[BOLT RESULTS INSERT]
	--END --[BOLT RESULTS INSERT END]

	--[BOLT GROUP INSERT]