	BEGIN --[CCIPLATE MATERIAL INSERT BEGIN]
	--[CCIPLATE MATERIAL INSERT]
	END --[CCIPLATE MATERIAL INSERT END]

	UPDATE conn.bridge_stiffeners
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel2ID=[ID]

	--[BRIDGE STIFFENER DETAIL INSERT]