BEGIN

INSERT INTO conn.connections ([CCIPLATE FIELDS]) 
	OUTPUT INSERTED.ID INTO @TopLevel
	VALUES([CCIPLATE VALUES])
	SELECT @TopLevelID=ID FROM @TopLevel

	--BEGIN --[CONNECTION INSERT BEGIN]
	--[CONNECTION INSERT]
	--END --[CONNECTION INSERT END]

	--BEGIN --[RESULTS INSERT BEGIN]
	--[RESULTS INSERT]
	--END --[RESULTS INSERT END]

	DELETE FROM @TopLevel
	DELETE FROM @SubLevel1
	DELETE FROM @SubLevel2
	DELETE FROM @SubLevel3
	DELETE FROM @SubLevel4
END