
BEGIN

	UPDATE conn.connections
	SET [UPDATE] 
	WHERE ID = [ID]

	--BEGIN --[CONNECTION UPDATE BEGIN]
	--[CONNECTION INSERT]
	--END --[CONNECTION UPDATE END]

	--BEGIN --[RESULTS UPDATE BEGIN]
	--[RESULTS INSERT]
	--END --[RESULTS UPDATE END]

END