	UPDATE conn.plates
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel1ID=[ID]

	--BEGIN --[PLATE DETAIL UPDATE BEGIN]
	--[PLATE DETAIL INSERT]
	--END --[PLATE DETAIL UPDATE END]

	--BEGIN --[BOLT GROUP UPDATE BEGIN]
	--[BOLT GROUP INSERT]
	--END --[BOLT GROUP UPDATE END]

	--BEGIN --[BRIDGE STIFFENER DETAIL UPDATE BEGIN]
	--[BRIDGE STIFFENER DETAIL INSERT]
	--END --[BRIDGE STIFFENER DETAIL UPDATE END]

	--[CONNECTION INSERT]