	--BEGIN --[BRIDGE STIFFENER DETAIL DELETE BEGIN]
	--[BRIDGE STIFFENER DETAIL INSERT]
	--END --[BRIDGE STIFFENER DETAIL DELETE END]

	--BEGIN --[BOLT GROUP DELETE BEGIN]
	--[BOLT GROUP INSERT]
	--END --[BOLT GROUP DELETE END]

	--BEGIN --[PLATE DETAIL DELETE BEGIN]
	--[PLATE DETAIL INSERT]
	--END --[PLATE DETAIL DELETE END]

DELETE FROM conn.plates WHERE ID = [ID]

	--[CONNECTION INSERT]