	INSERT INTO conn.plates ([CONNECTION FIELDS]) 
	OUTPUT INSERTED.ID INTO @SubLevel1
	VALUES([CONNECTION VALUES])
	SELECT @SubLevel1ID=ID FROM @SubLevel1

	--BEGIN --[PLATE DETAIL INSERT BEGIN]
	--[PLATE DETAIL INSERT]
	--END --[PLATE DETAIL INSERT END]

	--BEGIN --[BOLT GROUP INSERT BEGIN]
	--[BOLT GROUP INSERT]
	--END --[BOLT GROUP INSERT END]

	--BEGIN --[BRIDGE STIFFENER DETAIL INSERT BEGIN]
	--[BRIDGE STIFFENER DETAIL INSERT]
	--END --[BRIDGE STIFFENER DETAIL INSERT END]

	--BEGIN --[CONNECTION RESULTS INSERT BEGIN]
	--[CONNECTION RESULTS INSERT]
	--END --[CONNECTION RESULTS INSERT END]

	--[CONNECTION INSERT]