	BEGIN --[CCIPLATE MATERIAL INSERT BEGIN]
	--[CCIPLATE MATERIAL INSERT]
	END --[CCIPLATE MATERIAL INSERT END]

	UPDATE conn.plate_details
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel2ID=[ID]

	--BEGIN --[PLATE RESULTS INSERT BEGIN]
	--[PLATE RESULTS INSERT]
	--END --[PLATE RESULTS INSERT END]

	--BEGIN --[STIFFENER GROUP UPDATE BEGIN]
	--[STIFFENER GROUP INSERT]
	--END --[STIFFENER GROUP UPDATE END]

	--[PLATE DETAIL INSERT]