	UPDATE conn.stiffeners
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel3ID=[ID]

	--BEGIN --[STIFFENER DETAIL UPDATE BEGIN]
	--[STIFFENER DETAIL INSERT]
	--END --[STIFFENER DETAIL UPDATE END]

	--BEGIN --[STIFFENER RESULTS INSERT BEGIN]
	--[STIFFENER RESULTS INSERT]
	--END --[STIFFENER RESULTS INSERT END]

	--[STIFFENER GROUP INSERT]