	INSERT INTO conn.stiffeners ([STIFFENER GROUP FIELDS]) 
	OUTPUT INSERTED.ID INTO @SubLevel3
	VALUES([STIFFENER GROUP VALUES])
	SELECT @SubLevel3ID=ID FROM @SubLevel3

	--BEGIN --[STIFFENER DETAIL INSERT BEGIN]
	--[STIFFENER DETAIL INSERT]
	--END --[STIFFENER DETAIL INSERT END]

	--BEGIN --[STIFFENER RESULTS INSERT BEGIN]
	--[STIFFENER RESULTS INSERT]
	--END --[STIFFENER RESULTS INSERT END]

	--[STIFFENER GROUP INSERT]