
BEGIN

	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
		OUTPUT INSERTED.ID INTO @TopLevel
		VALUES([INSERT VALUES])
	SELECT @SubLevel1ID=ID FROM @SubLevel1

	--[ANCHOR BLOCK PROFILE]

	--[ANCHOR BLOCK SOIL PROFILE]

	--[ANCHOR BLOCK RESULTS]
END