
BEGIN

	--[ANCHOR BLOCK PROFILE]

	--[ANCHOR BLOCK SOIL PROFILE]

	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
		OUTPUT INSERTED.ID INTO @SubLevel2
		VALUES([INSERT VALUES])
	SELECT @SubLevel2ID=ID FROM @SubLevel2

	--[ANCHOR BLOCK RESULTS]
END