
BEGIN

INSERT INTO load.seismic ([SEISMIC FIELDS]) 
	OUTPUT INSERTED.ID INTO @TopLevel
	VALUES([SEISMIC VALUES])
	SELECT @TopLevelID=ID FROM @TopLevel

	DELETE FROM @TopLevel
	DELETE FROM @SubLevel1
	DELETE FROM @SubLevel2
	DELETE FROM @SubLevel3
	DELETE FROM @SubLevel4
END