BEGIN

	INSERT INTO [TABLE NAME] ([INSERT FIELDS]) 
		OUTPUT INSERTED.ID INTO @SubLevel2
		VALUES([INSERT VALUES])
	SELECT @SubLevel2ID=ID FROM @SubLevel2

	--[SECTION INSERT]

	--[BELLED INSERT]

	--[EMBEDDED INSERT]

END