	--BEGIN --[LEG REINFORCEMENT DETAIL UPDATE BEGIN]
	UPDATE tnx.memb_leg_reinforcement_details
	SET [UPDATE] 
	WHERE ID = [ID]
	Set @SubLevel1ID=[ID]

	--BEGIN --[LEG REINFORCEMENT DETAILS RESULTS INSERT BEGIN]
	--[LEG REINFORCEMENT DETAILS RESULTS INSERT]
	--END --[LEG REINFORCEMENT DETAILS RESULTS INSERT END]

	--END --[LEG REINFORCEMENT DETAIL UPDATE END]

	--[LEG REINFORCEMENT DETAIL INSERT]