	--BEGIN --[LEG REINFORCEMENT DETAIL INSERT BEGIN]
	INSERT INTO tnx.memb_leg_reinforcement_details ([LEG REINFORCEMENT DETAIL FIELDS]) 
	OUTPUT INSERTED.ID INTO @SubLevel1
	VALUES([LEG REINFORCEMENT DETAIL VALUES])
	SELECT @SubLevel1ID=ID FROM @SubLevel1

	--BEGIN --[LEG REINFORCEMENT DETAILS RESULTS INSERT BEGIN]
	--[LEG REINFORCEMENT DETAILS RESULTS INSERT]
	--END --[LEG REINFORCEMENT DETAILS RESULTS INSERT END]

	--END --[LEG REINFORCEMENT DETAIL INSERT END]

	--[LEG REINFORCEMENT DETAIL INSERT]