	INSERT INTO tnx.memb_leg_reinforcement_details ([LEG REINFORCEMENT DETAIL FIELDS]) 
	OUTPUT INSERTED.ID INTO @SubLevel1
	VALUES([LEG REINFORCEMENT DETAIL VALUES])
	SELECT @SubLevel1ID=ID FROM @SubLevel1

	--BEGIN --[LEG REINFORCEMENT DETAIL RESULTS INSERT BEGIN]
	--[LEG REINFORCEMENT DETAIL RESULTS INSERT]
	--END --[LEG REINFORCEMENT DETAIL RESULTS INSERT END]

	--[LEG REINFORCEMENT DETAIL INSERT]