BEGIN

INSERT INTO tnx.memb_leg_reinforcement ([LEG REINFORCEMENT FIELDS]) 
	OUTPUT INSERTED.ID INTO @TopLevel
	VALUES([LEG REINFORCEMENT VALUES])
	SELECT @TopLevelID=ID FROM @TopLevel

	--[LEG REINFORCEMENT DETAIL INSERT]

	DELETE FROM @TopLevel
	DELETE FROM @SubLevel1
	DELETE FROM @SubLevel2
	DELETE FROM @SubLevel3
	DELETE FROM @SubLevel4
END