BEGIN

	--BEGIN --[LEG REINFORCEMENT DETAIL DELETE BEGIN]
	--[LEG REINFORCEMENT DETAIL INSERT]
	--END --[LEG REINFORCEMENT DETAIL DELETE END]

DELETE FROM tnx.memb_leg_reinforcement WHERE ID = [ID]

END