BEGIN

	UPDATE tnx.memb_leg_reinforcement
	SET [UPDATE] 
	WHERE ID = [ID]

	--BEGIN --[LEG REINFORCEMENT DETAIL UPDATE BEGIN]
	--[LEG REINFORCEMENT DETAIL INSERT]
	--END --[LEG REINFORCEMENT DETAIL UPDATE END]

	--BEGIN --[RESULTS UPDATE BEGIN]
	--[RESULTS INSERT]
	--END --[RESULTS UPDATE END]

END