
BEGIN
	
	--[SOIL PROFILE INSERT]

INSERT INTO fnd.pile ([FOUNDATION FIELDS]) 
	OUTPUT INSERTED.ID INTO @Top
	VALUES([FOUNDATION VALUES])
	SELECT @TopID=TopID FROM @Top

	--[SOIL LAYER]
	--[RESULTS]

	--BEGIN --[SOIL LAYER INSERT BEGIN]
	--[SOIL LAYER INSERT]
	--END --[SOIL LAYER INSERT END]

	--DELETE FROM @Prev
END