
BEGIN

	--BEGIN --[SOIL PROFILE UPDATE BEGIN]
	--[SOIL PROFILE INSERT]
	--END --[SOIL PROFILE UPDATE END]

	UPDATE fnd.pile
	SET [UPDATE] 
	WHERE ID = [ID]

	--BEGIN --[SOIL LAYER UPDATE BEGIN]
	--[SOIL LAYER INSERT]
	--END --[SOIL LAYER UPDATE END]

	--BEGIN --[PILE LOCATION UPDATE BEGIN]
	--[PILE LOCATION INSERT]
	--END --[PILE LOCATION UPDATE END]

	--BEGIN --[RESULTS UPDATE BEGIN]
	--[RESULTS INSERT]
	--END --[RESULTS UPDATE END]

END