
BEGIN
	
	--BEGIN --[SOIL PROFILE INSERT BEGIN]
	--[SOIL PROFILE INSERT]
	--END --[SOIL PROFILE INSERT END]

INSERT INTO fnd.pile ([FOUNDATION FIELDS]) 
	OUTPUT INSERTED.ID INTO @TopLevel
	VALUES([FOUNDATION VALUES])
	SELECT @TopLevelID=ID FROM @TopLevel

	--BEGIN --[SOIL LAYER INSERT BEGIN]
	--[SOIL LAYER INSERT]
	--END --[SOIL LAYER INSERT END]

	--BEGIN --[PILE LOCATION INSERT BEGIN]
	--[PILE LOCATION INSERT]
	--END --[PILE LOCATION INSERT END]

	--BEGIN --[RESULTS INSERT BEGIN]
	--[RESULTS INSERT]
	--END --[RESULTS INSERT END]

	DELETE FROM @TopLevel
	DELETE FROM @SubLevel1
	DELETE FROM @SubLevel2
	DELETE FROM @SubLevel3
	DELETE FROM @SubLevel4
END