
BEGIN
	--BEGIN --[PILE LOCATION DELETE BEGIN]
	--[PILE LOCATION INSERT]
	--END --[PILE LOCATION DELETE END]	

DELETE FROM fnd.pile WHERE ID = [ID]

	--BEGIN --[SOIL LAYER DELETE BEGIN]
	--[SOIL LAYER INSERT]
	--END --[SOIL LAYER DELETE END]

	--BEGIN --[SOIL PROFILE DELETE BEGIN]
	--[SOIL PROFILE INSERT]
	--END --[SOIL PROFILE DELETE END]


END