	BEGIN

		INSERT INTO fnd.soil_profile ([SOIL PROFILE FIELDS]) 
			OUTPUT INSERTED.ID INTO @SubLevel1
			VALUES([SOIL PROFILE VALUES])
		SELECT @SubLevel1ID=ID FROM @SubLevel1

		--[SOIL LAYER INSERT]

END