'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Testing_Winform.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property about() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CCIplate__4_1_2_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIplate__4_1_2_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CCIpole__4_5_8_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CCIpole__4_5_8_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CCISeismic__3_3_9_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CCISeismic__3_3_9_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property charttype_line() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("charttype_line", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property construction_svgrepo_com__1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("construction_svgrepo_com__1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Drilled_Pier_Foundation__5_0_5_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Drilled_Pier_Foundation__5_0_5_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Guyed_Anchor_Block_Foundation__4_0_0_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Guyed_Anchor_Block_Foundation__4_0_0_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property highimportance() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("highimportance", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro_1669842870() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro-1669842870", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property l_intro_1658899230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l-intro-1658899230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ladder_svgrepo_com() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ladder_svgrepo_com", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Leg_Reinforcement_Tool__10_0_4_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Leg_Reinforcement_Tool__10_0_4_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property navigateBack() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("navigateBack", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property navigateForward() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("navigateForward", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property navigateUp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("navigateUp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pier_and_Pad_Foundation__4_1_1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pier_and_Pad_Foundation__4_1_1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pile_Foundation__2_2_1_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pile_Foundation__2_2_1_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property rightangleconnector() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("rightangleconnector", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SST_Unit_Base_Foundation__4_0_3_() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SST_Unit_Base_Foundation__4_0_3_", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        '''</summary>
        Friend ReadOnly Property warning() As DevExpress.Utils.Svg.SvgImage
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,DevExpress.Utils.Svg.SvgImage)
            End Get
        End Property
    End Module
End Namespace
