
BEGIN

	INSERT INTO pole.pole ([GENERAL POLE FIELDS]) 
		OUTPUT INSERTED.ID INTO @TopLevel
		VALUES([GENERAL POLE VALUES])
		SELECT @TopLevelID=ID FROM @TopLevel


		--[UNREINF SECTION INSERT]

		--[REINF SECTION INSERT]

		--[REINF GROUP INSERT]

		--[INT GROUP INSERT]

		--[RESULT INSERT]


	DELETE FROM @TopLevel	--CCIpole General
	DELETE FROM @SubLevel1	--Reinf Groups / Int Groups
	DELETE FROM @SubLevel2	--Reinf DB
	DELETE FROM @SubLevel3	--Bolt DB
	DELETE FROM @SubLevel4	--Matl DB

END