
BEGIN

	DELETE FROM pole.pole WHERE ID = [ID]

	--UnreinfSectionDNU	BEGIN --[UNREINF SECTION DELETE BEGIN]
	--UnreinfSectionDNU		[UNREINF SECTION DELETE]
	--UnreinfSectionDNU	END --[UNREINF SECTION DELETE END]

	--ReinfSectionDNU	BEGIN --[REINF SECTION DELETE BEGIN]
	--ReinfSectionDNU		[REINF SECTION DELETE]
	--ReinfSectionDNU	END --[REINF SECTION DELETE END]

	--ReinfGroupDNU	BEGIN --[REINF GROUP DELETE BEGIN]
	--ReinfGroupDNU		[REINF GROUP DELETE]
	--ReinfGroupDNU	END --[REINF GROUP DELETE END]

	--IntGroupDNU	BEGIN --[INT GROUP DELETE BEGIN]
	--IntGroupDNU		[INT GROUP DELETE]
	--IntGroupDNU	END --[INT GROUP DELETE END]

	--ResultsDNU	BEGIN --[RESULTS DELETE BEGIN]
	--ResultsDNU		[RESULTS DELETE]
	--ResultsDNU	END --[RESULTS DELETE END]

END