
BEGIN

	UPDATE pole.pole
	SET [UPDATE] 
	WHERE ID = [ID]

	--UnreinfSectionDNU	BEGIN --[UNREINF SECTION UPDATE BEGIN]
	--UnreinfSectionDNU		[UNREINF SECTION UPDATE]
	--UnreinfSectionDNU	END --[UNREINF SECTION UPDATE END]

	--ReinfSectionDNU	BEGIN --[REINF SECTION UPDATE BEGIN]
	--ReinfSectionDNU		[REINF SECTION UPDATE]
	--ReinfSectionDNU	END --[REINF SECTION UPDATE END]

	--ReinfGroupDNU	BEGIN --[REINF GROUP UPDATE BEGIN]
	--ReinfGroupDNU		[REINF GROUP UPDATE]
	--ReinfGroupDNU	END --[REINF GROUP UPDATE END]

	--IntGroupDNU	BEGIN --[INT GROUP UPDATE BEGIN]
	--IntGroupDNU		[INT GROUP UPDATE]
	--IntGroupDNU	END --[INT GROUP UPDATE END]

	--ResultsDNU	BEGIN --[RESULTS UPDATE BEGIN]
	--ResultsDNU		[RESULTS UPDATE]
	--ResultsDNU	END --[RESULTS UPDATE END]

END